name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      # https://markphelps.me/posts/speed-up-your-go-builds-with-actions-cache/
      - id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"
      
      # Cache go build cache, used to speedup go test
      - name: Go Build Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}

      # Cache go mod cache, used to speedup builds
      - name: Go Mod Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-mod-${{ hashFiles('**/go.sum') }}
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Run unit tests
        run: |
          go get ./...
          go test ./... -v

      - name: Validate terraform config
        run: |
          find . -maxdepth 2 -type f -name "*.tf" -exec dirname "{}" \; | uniq | while read dir; do
            cd $dir
            terraform init
            terraform validate
            cd ..
          done